

Import("*")

python_version= env["python_version"]
print python_version

defines= {'PYTHON_VERSION_MAJOR' : int(python_version), 'PYTHON_VERSION_MINOR': int(python_version*10)%10 }



env.Append(CPPDEFINES=defines)
env.Append(CPPPATH=["/usr/include/boost141/", "/usr/include/python" + str(python_version) + "/" ])
#env.Append(LIBS=["boost_python-mt"])
env.Append(LIBPATH=["/usr/lib64/boost141/"])
## setups vars

py24_headers = [Glob("*.h*") ]


if ARGUMENTS.get("gfal_path",'0') !='0':
	tmp_path = ARGUMENTS.get("gfal_path",'0')
	env.Append(CPPPATH=[tmp_path+"/include/gfal2/" ])
	env.Append(LIBS=["gfal2"  ])	
	env.Append(LIBPATH=[tmp_path+"/lib64/", tmp_path+"/lib/"  ])	
else:
	env.ParseConfig("pkg-config --cflags --libs gfal2")





env.ParseConfig("pkg-config --cflags --libs glib-2.0")

boost_src = [  Glob("boost/python/object/src/*.cpp"), Glob("boost/python/object/src/object/*.cpp"), Glob("boost/python/object/src/converter/*.cpp") ]

py24_main_lib = env.SharedLibrary("libgfal2_python", Glob("*.cpp") + boost_src)
env.Depends(py24_main_lib, py24_headers)

py24_main_sym = env.Symlink("gfal2.so", py24_main_lib)
py24_main = [py24_main_lib + py24_main_sym ]


Return("py24_main")
